// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBAPA_OzRTZ0SuI5yl-4gLPfnZT5nXb-g',
    appId: '1:677880256454:web:aed71903507168e7f944c7',
    messagingSenderId: '677880256454',
    projectId: 'admin-web-96428',
    authDomain: 'admin-web-96428.firebaseapp.com',
    storageBucket: 'admin-web-96428.appspot.com',
    measurementId: 'G-Q1JTXR0RWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4LWM3O_1HddY5-mmbyR4FZEWxibh8JeQ',
    appId: '1:677880256454:android:b6a5aeb9d022138cf944c7',
    messagingSenderId: '677880256454',
    projectId: 'admin-web-96428',
    storageBucket: 'admin-web-96428.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7_IsEaPffrqVdcTS9owvpUGrL6IBc3lw',
    appId: '1:677880256454:ios:6343b4d26d43e51bf944c7',
    messagingSenderId: '677880256454',
    projectId: 'admin-web-96428',
    storageBucket: 'admin-web-96428.appspot.com',
    iosBundleId: 'com.example.adminWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7_IsEaPffrqVdcTS9owvpUGrL6IBc3lw',
    appId: '1:677880256454:ios:02dbde120cb90f99f944c7',
    messagingSenderId: '677880256454',
    projectId: 'admin-web-96428',
    storageBucket: 'admin-web-96428.appspot.com',
    iosBundleId: 'com.example.adminWeb.RunnerTests',
  );
}
